### PR TITLE
Create docker-compose.yml

### PR DESCRIPTION
**Pull request by oxr463**
```
docker-compose run rancher-monitoring-v1-to-v2
```

### CODE REVIEW

**Comment by bashofmann** [comment]
Thank you for your contribution. Before I merge this though: What is the value of having a docker-compose file for this project? It's not like you can run this script as a service. It's just a one-off cli tool.

**Comment by oxr463** [comment]
> Thank you for your contribution. Before I merge this though: What is the value of having a docker-compose file for this project? It's not like you can run this script as a service. It's just a one-off cli tool.

I had a call with a customer and it took a bit of time walking them through getting a docker image built. I added the docker-compose file to simplify that.

**Comment by bashofmann** [comment]
How about putting the `docker build` and `docker run` commands into the README instead? We could also add a small Makefile for it.`docker-compose` is not the right tool to just build an image, I think.

**Comment by oxr463** [comment]
> How about putting the `docker build` and `docker run` commands into the README instead? We could also add a small Makefile for it.`docker-compose` is not the right tool to just build an image, I think.

That works for me. Something I can easily copy and paste to get them up and running.

**Comment by bashofmann** [comment]
Added documentation with https://github.com/bashofmann/rancher-monitoring-v1-to-v2/commit/0b8bdfb40d1540774ee7a600fb9d57f405b01beb

**Pull request closed without merging**
